/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lista01;

public class App {
    public String getGreeting() {
        ObjectMapper ObjectMapper = new ObjectMapper();
    }
}
